### ISSUE TITLE
Possibility to add TAG repos to CLOTributor

### ISSUE THREAD

**Issue by aliok** [cncf/clotributor#303]
How can I add a TAG's repo to CLOTributor?

It would be nice to list this issue there for example: https://github.com/cncf/tag-contributor-strategy/issues/140

**Comment by tegioz** [comment]
Hi @aliok

One way of handling this would be to add a `CNCF TAGs` project (or any other similar name that fits better) and include that repo (and potentially others) to it. It was originally designed for projects in the sandbox/incubating/graduated path, but I don't see any major problem with this. Maybe something like this:

```yaml
- name: cncf-tags
  display_name: CNCF TAGs
  description: CNCF Technical Advisory Groups
  repositories:
    - name: tag-contributor-strategy
      url: https://github.com/cncf/tag-contributor-strategy
      check_sets: []
      exclude:
        - clomonitor
```

We could exclude it from CLOMonitor to avoid confusions with the rest of the CNCF projects. There is one detail we'd need to address first though: some fields, like the project's maturity, are required, and they don't fit well for a case like this. So we should probably make them optional.

What do you think about adding a project like that @caniszczyk?

**Comment by aliok** [comment]
Thanks @tegioz for the quick response.

I like your YAML-driven visualization, it helps understanding better.

I like the approach, except TAG Contributor Strategy has 2 repos that it owns and I would prefer having both indexed by CLOTributor:
- https://github.com/cncf/tag-contributor-strategy
- https://github.com/cncf/mentoring

How about having a separate project for each TAG? Something like: 

```yaml
- name: cncf-tag-contributor-strategy
  display_name: CNCF TAG Contributor Strategy
  description: CNCF TAG Contributor Strategy
  repositories:
    - name: tag-contributor-strategy
      url: https://github.com/cncf/tag-contributor-strategy
      check_sets: []
      exclude:
        - clomonitor
    - name: mentoring-wg
      url: https://github.com/cncf/tag-contributor-strategy
      check_sets: []
      exclude:
        - clomonitor
- name: cncf-tag-env-sustainability
  display_name: CNCF TAG Environmental Sustainability
  description: CNCF TAG Environmental Sustainability
  repositories:
    - name: cncf-tag-env-sustainability
      url: https://github.com/cncf/tag-env-sustainability/
      check_sets: []
      exclude:
        - clomonitor
```

Altough TAG Contributor Strategy might be the only exception having 2 repositories, another effect of separation is that it might be better to not put tasks from various TAGs under the same bucket. 

For example, if there's only 1 project for all TAGs, when I go to CLOTributor and click on `CNCF-TAGs` project there, I would see tasks from TAG-Security, TAG-Env-Sustainibility, TAG-Network, etc. Tasks in these TAGs can be pretty irrelevant to each other.
